### ISSUE TITLE
Makefile should be uppercase.

### ISSUE THREAD

**Issue by mdclyburn** [fkmclane/energia-makefile#1]
This also places it near the top of the file listing when in a sorted list.

**Comment by lilyinstarlight** [comment]
I do appreciate the logic, but I still prefer all lowercase filenames since they are easier to read.

**Comment by robertu94** [comment]
This is a real issue. It should be fixed because it is more portable.

**Comment by lilyinstarlight** [comment]
It isn't more portable because this is very specifically a GNU makefile as it uses several of the extensions.
